### ISSUE TITLE
TMX file loading does not work

### ISSUE THREAD

**Issue by totallyeviljake** [Cocos2DXNA/cocos2d-xna#23]
This is the tile map test, and the TMX file is not loading via the content manager. TMX is a non-processed file format that uses the Text processor.

**Comment by darmie** [comment]
@totallyeviljake Please can I get a concise tutorial on how to implement Tiled TMX in Cocos2d-XNA , I am getting this error! 

```
An exception of type 'Microsoft.Xna.Framework.Content.ContentLoadException' occurred in cocos2d-xna.DLL but was not handled in user code

Additional information: Failed to load the asset file from terrain1
```

This is my code: 

```
 _tileMap = new CCTMXTiledMap("terrain1");

            _background = _tileMap.LayerNamed("Background");

            AddChild(_tileMap, -1);  
```
