### ISSUE TITLE
where's latest iOS nuget package??

### ISSUE THREAD

**Issue by imkow** [Cocos2DXNA/cocos2d-xna#451]
cannot find latest iOS package on this feed: http://nuget.cocos2dxna.com/nuget

**Comment by imkow** [comment]
2015 now, can we expect iOS latest nuget package soon? thanks

**Comment by totallyeviljake** [comment]
Only if you can tell me how to get NuGet to work on a Mac! I have had no success with that aspect. The build is working now, just no NuGet packaging. The scripts are in the repository.

**Comment by totallyeviljake** [comment]
i give up on the mac. i installed the iOS VS support and will setup the nightly build to use that instead. that should allow us to push up the iOS NuGet packages.

**Comment by totallyeviljake** [comment]
I have to manually update this, and now 1.6 is up on the nuget.cocos2dxna.com server.
