### ISSUE TITLE
Support for CocosStudio?

### ISSUE THREAD

**Issue by darmie** [Cocos2DXNA/cocos2d-xna#472]
Hi, I would like to use this framework for Windows Phone 8 development, I couldn't find any test code for Cocos Studio extension in Cocos2d-xna. Would this feature be supported? When would it be supported?

**Comment by totallyeviljake** [comment]
Cocos Studio can write out the CBI format, which is the old cocos2d-x v2 "cocos builder" format. 

The new cocos2d v3 extensions are not supported in cocos2d-xna. Therefore any direct support for cocos studio will require supporting the v3 changes, which we have started working on, but we are not ready for any release yet.

**Comment by totallyeviljake** [comment]
This is a duplicate of #444

**Comment by darmie** [comment]
OK thank you. I'll anticipate a release.
