### ISSUE TITLE
wrong rectangle size in Texture2D.PlatformGetData for GL.ReadPixels

### ISSUE THREAD

**Issue by grishaandrianov** [Cocos2DXNA/cocos2d-xna#473]
https://github.com/Cocos2DXNA/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs#L241

should be like this:

            if (rect.HasValue)
            {
                x = rect.Value.X;
                y = rect.Value.Y;
                width = rect.Value.Width;
                height = rect.Value.Height;
            }
            GL.ReadPixels(x, y, width, height, this.glFormat, this.glType, data);

**Comment by totallyeviljake** [comment]
Your suggestion is exactly how the our fork of MonoGame has it. Make sure you have updated your submodule.

You can easily update the submodule using the command line:
cd cocos2d-xna
git pull
cd MonoGame
git checkout develop
git pull
cd ThirdParty
cd Dependencies
git checkout master
git pull

after those commands you will have the most up to date MonoGame and cocos2d-xna from the master. 

If you are using stable, then it should work as well.

**Comment by totallyeviljake** [comment]
oh wait, I see the difference:

rect.Value.Width

we have

this.Width

**Comment by totallyeviljake** [comment]
I have fixed it in our fork and updated the master with the new submodule guid.
